name: tierrating
services:
  server:
    image: ghcr.io/ratzzfatzz/tierrating:latest
    restart: unless-stopped
    ports:
      - 8080:8080
  ui:
    image: ghcr.io/ratzzfatzz/tierrating-ui:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      API_URL: 'http://server:8080'

networks:
  tierrating-network:
    driver: bridge
